### ISSUE TITLE
Missing vision-settings.xml

### ISSUE THREAD

**Issue by boroko** [opulo-inc/docs#103]
Not finding vision-settings.xml in the .zip of the openPnP folder for version 2.2.0 [Release v2.2.0 - PCB Staging Plate, Vacuum Sensor Interposer, CAD Adjustments · opulo-inc/lumenpnp (github.com)](https://github.com/opulo-inc/lumenpnp/releases/tag/v2.2.0)  

Referenced in https://docs.opulo.io/openpnp/calibration/1-import-config/#windows

**Comment by gabeseltzer** [comment]
Sorry about that! OpenPnP added the vision settings file after we started making releases, so it took a little while for us to include it in the release zip. You can use the default pipelines or grab one from the [3.0.0](https://github.com/opulo-inc/lumenpnp/releases/tag/v3.0.0) release.
