### ISSUE TITLE
V3 assembly instruction errors

### ISSUE THREAD

**Issue by ad6fp** [opulo-inc/docs#128]
In the "Wiring" section steps 15-18 the motor cables are shown as labeled LH and RH, mine were labeled LM and RM.

In the "Wiring" section step 34 the strain relief is attached with hardware that was already inserted, my strain relief had no hardware already inserted and there was not sufficient additional hardware in the kit.

In the OpenPnP section it should be mentioned to remove the dust covers from the cameras.

**Comment by gabeseltzer** [comment]
The wiring steps 15-18, I already fixed from the suggestion of https://github.com/opulo-inc/docs/issues/85.

For the strain relief, I'm not 100% sure what's wrong with the docs. I looked it over and it does look like we tell folks to install it at the correct time. Perhaps Gary was missing some screws and T-slot nuts in his kit, and that's it?

And I added notes about lens caps in https://github.com/opulo-inc/docs/pull/102

Gonna mark this as closed. If there's something I missed please let me know!
