### ISSUE TITLE
Sub-assemblies  should be at the beggining of the guide

### ISSUE THREAD

**Issue by kaklik** [opulo-inc/docs#14]
There should be only one guide for the assembly Belt Tension Arm (FDM-0037) which should be linked from every use of this part. 

Additionally, the whole assembly guide should start with the requirement to build all these simple sub-assemblies (e.g. mounting of the pulley on the motor).  Assembly of the third  Belt Tension Arm separately is much more annoying than building all three at one time. Because the screws should not be searched again, tools should be used in the same way at one time... etc.

**Comment by gabeseltzer** [comment]
Thanks for the feedback, we did this!
