### ISSUE TITLE
LumenPnP Assembly

### ISSUE THREAD

**Issue by DavePaulsen** [opulo-inc/docs#2]
Should there be an O-ring on the screw end of the CP40 nozzle holder where it attaches to the NEMA11 hollow shaft stepper motor (like there is on the Pneumatic Coupler mounted on the other end of the stepper).

**Comment by gabeseltzer** [comment]
just double-checked mine. There is no o-ring on the screw end.
![image](https://user-images.githubusercontent.com/1627557/194946766-232a81a6-ddb3-4d74-96d0-ce5a8b48523a.png)
