### ISSUE TITLE
PCB-04, missing install instructions

### ISSUE THREAD

**Issue by bangell** [opulo-inc/docs#25]
Looking at a picture it looks like pcb-04 mounts on A and B above the camera on the build plate, however the top bolt interferes wit the pcb.  looks like there is a notch out of the pcb for that bolt, is this correct?

**Comment by gabeseltzer** [comment]
Mounting the datum board (PCB-04) is described in the [OpenPnP section of the guide.](https://docs.opulo.io/openpnp/calibration/homing-fiducial/)
