### ISSUE TITLE
Attaching Belts

### ISSUE THREAD

**Issue by fabiankropp** [opulo-inc/docs#34]
Hi 

in number two, a good and easy way to pass the belt is pushing a cable tie in from the outside an let the belt rid on it to come out 
![IMG_1792](https://user-images.githubusercontent.com/3583759/189889259-b497b024-d70d-4c3d-923d-a7c8eebd061e.jpeg)

See the image attached :-)

BR 
Fabian

**Comment by gabeseltzer** [comment]
Thanks, I've added the tip to the guide. I'm leaving out the picture just for consistency in the guide, and I think the instructions are clear.
