### ISSUE TITLE
Sheathing the Umbilicals - Cable length in chapter 6. 

### ISSUE THREAD

**Issue by fabiankropp** [opulo-inc/docs#39]
in number 6 my measures would be:

DL 14 inches.
LM 14 inches (which may cause shortage on the other end)

**Comment by gabeseltzer** [comment]
Thanks for the feedback. I'm looking to see if we get more feedback about needing to change these steps, so I'll leave this open for now.

**Comment by gabeseltzer** [comment]
Closing this since we haven't had any more feedback about this :)
