### ISSUE TITLE
Tubes on step 31 (semi-wiring page) image needs updated

### ISSUE THREAD

**Issue by Mitchwich** [opulo-inc/docs#65]
The old image shows LH on top and RH on the bottom. This has been swapped in manufacturing to prevent having to twist hoses more than necessary. Now it has RH on the top and LH on the bottom. New photos have been added to google photos shared folder for product photos. Thank you!

**Comment by gabeseltzer** [comment]
Thanks! I did some photoshop to cover up the differences and added a line to explain why some photos are not fixed
