### ISSUE TITLE
Vacuum Sensors under Actuator Check is misleading

### ISSUE THREAD

**Issue by thinkl33t** [opulo-inc/docs#66]
This section gives a variety of options for gcodes you need to run to test the vacuum sensors.  None of them are correct for my printer, and i only found this out by going to the discord and searching historic messages.

I'd recommend opening this section with a description of the options for gcodes:
- v2 mainboard?
- interposers / no interposers (G4 or G2)
- finding the correct A value for your sensors specifically (as this can be anywhere between 0 and 7, and afaict can be expressed in binary or decimal) (mine is A0, but only A110 is shown in the docs)

Only once the user has identified enough of that for them to be able to talk to the i2c sensor should they attempt to test vacuum

**Comment by gabeseltzer** [comment]
@sphawes can you comment on the acceptable range for the A values? I can add that to the docs page. The interposers are already documented on the page, and the whole page is designed for v3 motherboards (not the v4 motherboards that ship with LumenPnP v3 semi-assembled machines)
