### ISSUE TITLE
change photo of bottom camera in Docs

### ISSUE THREAD

**Issue by Mitchwich** [opulo-inc/docs#89]
Was talking with Stephen and noticed this photo is of an older model. the newer one is much more recessed. Could we update this photo to match what the customers are getting in the box currently?

**Comment by gabeseltzer** [comment]
@sphawes are you able to get me a photo for this?

**Comment by gabeseltzer** [comment]
@sphawes ping again, can you get me a photo? Thanks!

**Comment by sphawes** [comment]
@gabeseltzer Added to the docs google photos drive, plus attached here! it's just a single pic without a nozzle tip above, if you need more specific images to do the swap lmk, but a pass through the docs seems like this should be an acceptable replacement for the existing close ups of the bottom cam
![PXL_20230523_201137268](https://github.com/opulo-inc/docs/assets/1865862/37af1f4a-3186-440a-a861-69754dea4e8a)

**Comment by gabeseltzer** [comment]
There's a lot of photos of the bottom camera so I just decided to put a disclaimer early on that new units will look slightly different. Someday it would be nice to do fresh photos but I think confusion is minimal :)
